In [5]:
import numpy as np
import pandas as pd


from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier


In [6]:
df = pd.read_csv('Titanic-Dataset.csv')

In [7]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [9]:
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

In [10]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,22.0,1,0,7.2500,S
1,1,1,female,38.0,1,0,71.2833,C
2,1,3,female,26.0,0,0,7.9250,S
3,1,1,female,35.0,1,0,53.1000,S
4,0,3,male,35.0,0,0,8.0500,S


In [11]:
x_train, x_test, y_train, y_test = train_test_split(
    df.drop(columns=['Survived']),
    df['Survived'],
    test_size=0.2,
    random_state=42
)

#y is survived column

In [12]:
x_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5000,S
733,2,male,23.0,0,0,13.0000,S
382,3,male,32.0,0,0,7.9250,S
704,3,male,26.0,1,0,7.8542,S
813,3,female,6.0,4,2,31.2750,S
...,...,...,...,...,...,...,...
106,3,female,21.0,0,0,7.6500,S
270,1,male,NaN,0,0,31.0000,S
860,3,male,41.0,2,0,14.1083,S
435,1,female,14.0,1,2,120.0000,S


In [13]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [14]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [17]:
# applying imputation

si_age = SimpleImputer() #filling with mean becouse age is numerical and most frequent is not good for numerical
si_embarked = SimpleImputer(strategy='most_frequent') #filling with most frequent becouse embarked is categorical

x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])

x_test_age = si_age.transform(x_test[['Age']])
x_test_embarked = si_embarked.transform(x_test[['Embarked']])




In [18]:
x_train_age

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25

In [19]:
x_train_embarked

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

In [26]:
# categorical encoding (onehot)

ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False, handle_unknown='ignore')


x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked = ohe_embarked.fit_transform(x_train[['Embarked']])

x_test_sex = ohe_sex.transform(x_test[['Sex']])
x_test_embarked = ohe_embarked.transform(x_test[['Embarked']])

In [27]:
x_train_embarked

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [28]:
x_train_rem = x_train.drop(columns=['Age', 'Sex', 'Embarked'])
x_test_rem = x_test.drop(columns=['Age', 'Sex', 'Embarked'])

In [29]:
x_train_transformed = np.concatenate(
    [x_train_rem, x_train_age, x_train_sex, x_train_embarked],
    axis=1 )



In [30]:
x_test_transformed = np.concatenate(
    [x_test_rem, x_test_age, x_test_sex, x_test_embarked],
    axis=1 )

In [31]:
x_train_transformed = np.concatenate(
    [x_train_rem, x_train_age, x_train_sex, x_train_embarked],
    axis=1 )

x_test_transformed = np.concatenate(
    [x_test_rem, x_test_age, x_test_sex, x_test_embarked],
    axis=1 )

In [32]:
x_test_transformed.shape

(179, 11)

In [33]:
clf = DecisionTreeClassifier()
clf.fit(x_train_transformed, y_train)

DecisionTreeClassifier()

In [34]:
y_pred = clf.predict(x_test_transformed)
y_pred

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score


In [38]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7653631284916201


In [39]:
import pickle

In [41]:
import os

# Create the directory if it doesn't exist to prevent errors
if not os.path.exists('model'):
    os.makedirs('model')

pickle.dump(ohe_sex, open('model/ohe_sex.pkl', 'wb'))
pickle.dump(ohe_embarked, open('model/ohe_embarked.pkl', 'wb')) 
pickle.dump(clf, open('model/clf.pkl', 'wb'))

In [45]:
x_train.head(2)

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5,S
733,2,male,23.0,0,0,13.0,S


-----
# PICKLE LOAD  DATA

In [42]:
import pickle
import numpy as np


In [43]:
ohe_sex = pickle.load(open('model/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('model/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('model/clf.pkl', 'rb'))


In [46]:
#assume user input
test_input = np.array([2,'male',31,0,0,28.5,5], dtype=object).reshape(1,7)

In [47]:
test_input_sex = ohe_sex.transform(test_input[:, [1]])
test_input_embarked = ohe_embarked.transform(test_input[:, [6]])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [49]:
test_input_embarked

array([[0., 0., 0., 0.]])

In [51]:
# do concatenation similar to training data
# order should be same as training data

---------
# now using pipeline

In [63]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.feature_selection import SelectKBest, chi2 

In [64]:
df = pd.read_csv('Titanic-Dataset.csv')


In [65]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


# plan
- missing values impute 
- onehot encoding
- scalling
- feature selection
- model traing using decision tree

In [66]:
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)


In [67]:
x_train, x_test, y_train, y_test = train_test_split(
    df.drop(columns=['Survived']),
    df['Survived'],
    test_size=0.2,
    random_state=42
)

In [68]:
x_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5000,S
733,2,male,23.0,0,0,13.0000,S
382,3,male,32.0,0,0,7.9250,S
704,3,male,26.0,1,0,7.8542,S
813,3,female,6.0,4,2,31.2750,S
...,...,...,...,...,...,...,...
106,3,female,21.0,0,0,7.6500,S
270,1,male,NaN,0,0,31.0000,S
860,3,male,41.0,2,0,14.1083,S
435,1,female,14.0,1,2,120.0000,S


In [69]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

1 step of pipeline

In [70]:
from sklearn.compose import ColumnTransformer

trf1 = ColumnTransformer([
    ('imputer_age', SimpleImputer(), [2]), # 2 is the age index
    ('imputer_embarked', SimpleImputer(strategy='most_frequent'), [6]) # 6th one is embarked index
], remainder='passthrough')

2 onehotencoding

In [71]:
trf2 = ColumnTransformer([
    ('onehot_sex_embarked', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [1,6]),
], remainder='passthrough') # passthough means other columns remain unchanged


scallling

In [72]:
trf3 = ColumnTransformer([
    ('scaler', MinMaxScaler(), slice(0,8)), # scaling all columns except onehot encoded columns
])

4 feature selection

In [73]:
trf4 = SelectKBest(score_func=chi2, k=5) # select top 5 features

5 decision tree

In [74]:
trf5 = DecisionTreeClassifier()

# CREATING PIPELINE

In [75]:
pipe = Pipeline([
    ('imputation', trf1),
    ('encoding', trf2),
    ('scaling', trf3),
    ('feature_selection', trf4),
    ('classification', trf5)
])

In [77]:
#train the pipeline
pipe.fit(x_train, y_train)

Pipeline(steps=[('imputation',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('imputer_age',
                                                  SimpleImputer(), [2]),
                                                 ('imputer_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('scaling',
                 ColumnTransformer(transformers=[('scaler', MinMaxScaler(),
                                                  slice(0, 8, None))])),
                ('feature_selection',
                 SelectKBest(k=5,
                             score_func=<function chi2 at 0x0000027B0EC24900>)),
                ('classification', DecisionTreeClassifier())])

In [78]:
pipe.named_steps

{'imputation': ColumnTransformer(remainder='passthrough',
                   transformers=[('imputer_age', SimpleImputer(), [2]),
                                 ('imputer_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'encoding': ColumnTransformer(remainder='passthrough',
                   transformers=[('onehot_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'scaling': ColumnTransformer(transformers=[('scaler', MinMaxScaler(), slice(0, 8, None))]),
 'feature_selection': SelectKBest(k=5, score_func=<function chi2 at 0x0000027B0EC24900>),
 'classification': DecisionTreeClassifier()}

In [90]:
# code here visualization backtrak debugging
pipe.named_steps['imputation'].transformers_[1][1].statistics_

array(['S'], dtype=object)

In [79]:
from sklearn import set_config
set_config(display='diagram')

In [80]:
y_pred = pipe.predict(x_test)

In [81]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

In [82]:
print("Accuracy:", accuracy)

Accuracy: 0.6256983240223464


In [91]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, x_train, y_train, cv=5, scoring='accuracy').mean()

np.float64(0.6391214419383433)

In [94]:
params = (
    "classification__max_depth":[1,2,3,4,5,None]
)

SyntaxError: invalid syntax (4098829879.py, line 2)

In [95]:
import pickle
pickle.dump(pipe, open('model/sklearn_pipeline.pkl', 'wb'))